In [2]:
import numpy as np
import math

In [3]:
a = [[1, 2, 3], [6, 5, 4]]
arr = np.array(a)
arr

array([[1, 2, 3],
       [6, 5, 4]])

In [4]:
x = np.array([10, 20, 30, 40])
y = np.array([1,  2,  3,  4 ])
print(x - y)
print(x * y)

[ 9 18 27 36]
[ 10  40  90 160]


In [5]:
np.shape(arr)

(2, 3)

In [6]:
np.size(arr)

6

In [7]:
tempInC = np.array([12, 15, 0, 7, 8, -20])
tempInF = tempInC * 9 / 5 + 32
tempInF

array([53.6, 59. , 32. , 44.6, 46.4, -4. ])

In [8]:
tempCond = np.array(tempInC <= 0)
tempCond

array([False, False,  True, False, False,  True])

In [9]:
tempInC % 2 == 0

array([ True, False,  True, False,  True,  True])

In [10]:
# For matrix dot multiplication, we use '@', while for normal element wise multiplcation, we use '*'

a = np.array([[1, 2], [3, 4]])
b = np.array([[4, 3], [2, 1]])

print(a * b)
print(a @ b)

[[4 6]
 [6 4]]
[[ 8  5]
 [20 13]]


In [11]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7])
a[:5]

array([0, 1, 2, 3, 4])

In [12]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7])
a[2:5]

array([2, 3, 4])

In [13]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a[:2, 1:3]

array([[2, 3],
       [5, 6]])

In [15]:
sub = a[:2, 1:3]
sub[0, 0] = 100
a  # Changes reflected in original array also

array([[  1, 100,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

Working With Dataset

In [17]:
# from hamcrest import none


# d = np.genfromtxt('./Data Sets/cars.csv', delimiter=',', dtype=none, skip_header=1, names=('Make', 'Model'))
# # d[0: 10]